- projects/material-addons/package.json
Der Angular Compiler hat Probleme, weil eine falsche Version von Material verwendet wird und das passiert, weil die Library ihr eigene Material version zieht
> Move Material to Peer Dependencies

- projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
- src/app/example-components/read-only-field-wrapper/read-only-field-wrapper.component.html
- src/app/example-components/read-only-field-wrapper/read-only-field-wrapper.component.ts
- src/app/example-components/read-only-field/read-only-field.component.html
Add an additional @input to explicitly enable number conversion, eg was added:
`@Input('formatNumber') formatNumber = false;`
Added in both mad-readonly-form-field and mad-readonly-form-field-wrapper
closes #46
> issue-46: Fixed default formatting of readOnly form field

- projects/material-addons/src/lib/card/card.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
- src/app/example-components/card-editable/card-editable.component.html
- src/app/example-components/card-editable/card-editable.component.ts
Fixes missing labels in read only mode of mad-readonly-form-field-wrapper when label text is loaded async
Closes #52 
mad-readonly-form-field-wrapper
> Fix missing label when using mad-readonly-form-field-wrapper

- projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
- src/app/example-components/read-only-field-wrapper/read-only-field-wrapper.component.html
- src/app/example-components/read-only-field/read-only-field.component.html
add id as input for mad-readonly-form-field
mad-readonly-form-field
mad-readonly-form-field-wrapper
> add an id to readonly form field

- projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
Fixes the issue with the resetting of an input which value is initially not set. See issue #85 for the demo (https://stackblitz.com/edit/material-addons-numeric-field?file=src/app/app.component.ts)
madNumericField directive
> Fixed resetting inputs to empty value that use the madNumericField directive (#85)

- projects/material-addons/src/lib/quick-list/base-quick-list.component.ts
- projects/material-addons/src/lib/quick-list/quick-list-compact/quick-list-compact.component.html
- projects/material-addons/src/lib/quick-list/quick-list-compact/quick-list-compact.component.ts
- projects/material-addons/src/lib/quick-list/quick-list.component.html
- projects/material-addons/src/lib/quick-list/quick-list.component.ts
- projects/material-addons/src/lib/quick-list/quick-list.module.ts
- src/app/app.module.ts
- src/app/component-demos/quick-list-demo/quick-list-demo.component.html
- src/app/component-demos/quick-list-demo/quick-list-demo.component.ts
- src/app/example-components/quick-list-compact-basic/quick-list-compact-basic.component.html
- src/app/example-components/quick-list-compact-basic/quick-list-compact-basic.component.scss
- src/app/example-components/quick-list-compact-basic/quick-list-compact-basic.component.ts
- src/app/example-components/quick-list-extended/quick-list-extended.component.ts
Enhancement of the quicklist as aligned with @d-m-s (#83 and #84)
1. Changed the behavior of the "trashbin-icon" when min items reached. Instead of disabling it the icon isn't being displayed anymore
2. Extracted the base functionality of the quick list to a base component and implemented the "quick list compact"
Material Addons Quicklist
> hide delete button if minItems reached instead of disabling it, extracted base functionality of quick list, implemented quick list compact (#83 & #84)

- package-lock.json
- projects/material-addons/src/lib/data-table/data-table-action.ts
- projects/material-addons/src/lib/data-table/data-table-column-header.ts
- projects/material-addons/src/lib/data-table/data-table.component.html
- projects/material-addons/src/lib/data-table/data-table.component.scss
- projects/material-addons/src/lib/data-table/data-table.component.ts
- projects/material-addons/src/lib/data-table/data-table.module.ts
- projects/material-addons/src/lib/data-table/data-table.ts
- projects/material-addons/src/public-api.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/component-demos/data-table-demo/data-table-demo.component.html
- src/app/component-demos/data-table-demo/data-table-demo.component.ts
- src/app/component-demos/table-demo/table-demo.component.html
- src/app/example-components/data-table/data-table-example-data.ts
- src/app/example-components/data-table/data-table.component.html
- src/app/example-components/data-table/data-table.component.scss
- src/app/example-components/data-table/data-table.component.ts
- src/assets/i18n/en.json
- src/navigation-entries.ts
DataTable #73 
New component DataTable
> add dataTable component and demo page

- projects/material-addons/src/lib/stepper/stepper.component.ts
As the next() can also be triggered when user is not in edit mode, doing so would result in marking non-editable fields with error
Stepper Component
> added flag to mark form fields as touched depending on client rules

- projects/material-addons/src/lib/data-table/data-table.component.html
- projects/material-addons/src/lib/data-table/data-table.component.ts
- src/app/example-components/data-table-example-data/data-table-example-data.ts
…ation pipe (#115)
There might be projects/use cases where a custom MissingTranslationHeader is implemented, which for example displays a message if a translation key is not found. When using the translate pipe, the labels in the data-table component will be translated and this will cause issues (because it would display that error/warning message in the table). 
By setting the [translateLabels]="false" the data-table will display the labels as they where passed, if [translateLabels]="true" (default), it will translate the labels
data-table
> added setting translateLabels to data-table to turn off/on the translations pipe

- package-lock.json
- projects/material-addons/src/lib/data-table/data-table.component.html
data table row action: when menu button is clicked, default action is executed (=row click event) before the menu is opened (affects material 15+)
data-table
> fix: data-table row actions

- jest.config.js
- package.json
- projects/material-addons/src/lib/button/danger-button/danger-button.component.spec.ts
- projects/material-addons/src/lib/button/flat-button/link.button.component.spec.ts
- projects/material-addons/src/lib/button/mad-button-group/mad-button-group.component.spec.ts
- projects/material-addons/src/lib/button/mad-button/mad-button.directive.spec.ts
- projects/material-addons/src/lib/card/card.component.html
- projects/material-addons/src/lib/card/card.component.spec.ts
- projects/material-addons/src/lib/data-table/data-table-columns-modal/data-table-columns-modal.component.spec.ts
- projects/material-addons/src/lib/data-table/data-table.component.spec.ts
- projects/material-addons/src/lib/numeric-field/number-format.service.spec.ts
- projects/material-addons/src/lib/numeric-field/numeric-field.directive.spec.ts
- projects/material-addons/src/lib/quick-list/base-quick-list.component.spec.ts
- projects/material-addons/tsconfig.spec.json
- setup-jest.ts
- tsconfig.spec.json
Add Jest configuration and unit tests for components, services and directives
The next unit test coverage achieved:
Not direct affect. Just added new spec files to the next:
- danger-button.component
- link.button.component
- mad-button.directive
- mad-button-group.component
- card.component
- data-table.component
- data-table-columns-modal.component
- number-format.service
- numeric-field.directive
- base-quick-list.component
> add jest unit tests

- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
- src/app/example-components/read-only-field/read-only-field.component.html
Add functionality of displaying content (other than text) inside the mad-readonly-form-field
ReadOnlyFormFieldComponent
> extend readonly form field

- projects/material-addons/src/lib/layout/sidebar/sidebar.component.ts
Allows for easier programmatic change of the collapsed property
Changes the collapsed property to be an Input. This way it's easier to influence it via code.
sidebar.component
> feat: Expose sidebar collapsed

- projects/material-addons/src/lib/quick-list/quick-list-compact/quick-list-compact.component.html
- projects/material-addons/src/lib/quick-list/quick-list-compact/quick-list-compact.component.ts
- projects/material-addons/src/lib/quick-list/quick-list.component.html
- projects/material-addons/src/lib/quick-list/reactive-form-quick-list-compact/reactive-form-quick-list-compact.component.html
- projects/material-addons/src/lib/quick-list/reactive-form-quick-list/reactive-form-quick-list.component.html
- projects/material-addons/src/themes/common/styles.scss
fixed alignment of icon-button within quick-list components and its derived classes
Fix alignment of buttons inside quick list and its derived components
quick-compact.component
quick-list-compact.component
reactive-form-quick-list.component
reactive-form-quick-list-compact.component
> removed general vertical-align styling for mat-icons

- projects/material-addons/src/lib/layout/toolbar/toolbar.component.html
- projects/material-addons/src/lib/layout/toolbar/toolbar.component.scss
mad-toolbar action button with icon displays incorrectly:
Added styled internal container for action button content
After fix looks like that:
- mad-toolbar
> Fix mad-toolbar main action buttons with icons

- .github/workflows/verify.yml
- projects/material-addons/src/lib/numeric-field/number-format.service.ts
- projects/material-addons/src/lib/numeric-field/numeric-field.module.ts
Change NumberFormatService to be providedIn 'root'.
This helps to override a dynamically set LOCALE_ID after changing.
number-format.service.ts
> Change NumberFormatService to be providedIn 'root'

- projects/material-addons/src/lib/file-upload/file-upload.component.html
- projects/material-addons/src/lib/file-upload/file-upload.component.ts
- src/app/component-demos/upload-demo/upload-demo-api-spec/upload-demo-api-spec.component.html
- src/app/component-demos/upload-demo/upload-demo-api-spec/upload-demo-api-spec.component.scss
- src/app/component-demos/upload-demo/upload-demo-api-spec/upload-demo-api-spec.component.ts
- src/app/component-demos/upload-demo/upload-demo.component.html
- src/app/component-demos/upload-demo/upload-demo.component.ts
- src/app/example-components/upload-file/upload-file.component.html
- src/app/example-components/upload-file/upload-file.component.ts
Change behavior of mad-file-upload component. 
- Added additional param as 'removable' which allows user to remove file from fileList
- In single mode new uploaded file replace previous one
- in single mode writes the uploaded file name in component
- In file list chips now have icon for remove file. Is available when 'removable' input param is in true
mad-file-upload
> update upload and add remove to mad-upload-file component

- README.md
- angular.json
- projects/material-addons/package.json
- projects/material-addons/src/version.ts
After update to v19 dist output was updated. So index.html and other source files were hidden under "browser" folder after build. This is why ghpages cannot find index.html in a root and demo page doesn't work
Components are not affected
> Fix dist output

- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
A callback method that is invoked immediately after the default change detector has completed one change-check cycle for a component's view.
Calling dedectChanges from within AfterViewChecked leads to a new callback on AfterViewChecked and thus the application gets stuck in a loop
https://angular.dev/api/core/AfterViewChecked
> Fix Endless Loop in Readonly FormField

- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.html
- projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
- projects/material-addons/src/lib/size-change/size-change.directive.ts
Optimizing complexity and performance of readonly form fields by migrating them to signals and killing the unit symbol injection. In order to ensure some behaviour/styling stays the same, the Size Change Directive was introduced.
Previously some calculations were done in life cycle hooks, which were also called when events like resizing happened. With migrating the readonly form field to signals and thereby getting rid of the life cycle hooks it's necessary to react to changes of the size of the component. This directive wraps a Resize Observer, which is Angular's recommended way to interact with such events.
Changed: Readonly Form Field Component
Created: Size Change Directive
> Migrate readonly-form-field to signals. Improve Performance
