porscheinformatik/material-addons

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE.md
pull_request_template.md

Added issue templates as described in issue #4. Additionaly, moved PR template and added contributing guide. 
None

add issue templates

---

projects/material-addons/tsconfig.lib.json

https://github.com/angular/angular/issues/35495#issuecomment-587110396

Add Import Helpers

---

package.json
projects/material-addons/src/lib/material-addons.module.ts
projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
projects/material-addons/src/lib/numeric-field/numeric-field.module.ts
projects/material-addons/src/public-api.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component-demos/numeric-field-demo/numeric-field-demo.component.html
src/app/component-demos/numeric-field-demo/numeric-field-demo.component.scss
src/app/component-demos/numeric-field-demo/numeric-field-demo.component.ts
src/app/example-components/numeric-field/numeric-field-wrapper.component.html
src/app/example-components/numeric-field/numeric-field-wrapper.component.scss
src/app/example-components/numeric-field/numeric-field-wrapper.component.ts
src/assets/i18n/en.json
src/navigation-entries.ts

numeric field directive & demo

---

README.md
package-lock.json
projects/material-addons/package.json
projects/material-addons/src/lib/numeric-field/number-format.service.ts
projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
projects/material-addons/src/lib/numeric-field/numeric-field.module.ts
projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.html
projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.css
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.html
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
src/app/component-demos/numeric-field-demo/numeric-field-demo.component.ts
src/app/example-components/numeric-field-wrapper/numeric-field-wrapper.component.html
src/app/example-components/numeric-field-wrapper/numeric-field-wrapper.component.ts

numeric fields are now editable as well
numeric fields, numeric field directive

editable numeric fields

---

projects/material-addons/src/lib/numeric-field/number-format.service.ts
projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
src/app/example-components/numeric-field-wrapper/numeric-field-wrapper.component.html

fixes numeric fields and units

---

projects/material-addons/src/lib/card/card.component.css
projects/material-addons/src/lib/card/card.component.html
projects/material-addons/src/lib/card/card.component.ts
projects/material-addons/src/lib/card/card.module.ts
projects/material-addons/src/lib/material-addons.module.ts
projects/material-addons/src/public-api.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component-demos/card-demo/card-demo.component.html
src/app/component-demos/card-demo/card-demo.component.scss
src/app/component-demos/card-demo/card-demo.component.ts
src/app/example-components/card-editable/card-editable.component.html
src/app/example-components/card-editable/card-editable.component.scss
src/app/example-components/card-editable/card-editable.component.ts
src/app/example-components/card-readonly/card-readonly.component.html
src/app/example-components/card-readonly/card-readonly.component.scss
src/app/example-components/card-readonly/card-readonly.component.ts
src/assets/i18n/en.json
src/navigation-entries.ts

New Card component
Card Component & Demo Page

card component & demo

---

projects/material-addons/src/lib/material-addons.module.ts
projects/material-addons/src/lib/quick-list/quick-list.component.html
projects/material-addons/src/lib/quick-list/quick-list.component.ts
projects/material-addons/src/lib/quick-list/quick-list.module.ts
projects/material-addons/src/public-api.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component-demos/quick-list-demo/quick-list-demo.component.html
src/app/component-demos/quick-list-demo/quick-list-demo.component.ts
src/app/example-components/quick-list/quick-list.component.html
src/app/example-components/quick-list/quick-list.component.scss
src/app/example-components/quick-list/quick-list.component.ts
src/assets/i18n/en.json
src/navigation-entries.ts

quicklist & example

---

projects/material-addons/src/lib/card/card.component.css
projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
projects/material-addons/src/themes/common/styles.scss

styles fixes for cards

---

projects/material-addons/src/lib/card/card.component.ts
src/app/example-components/card-editable/card-editable.component.html
src/app/example-components/card-editable/card-editable.component.ts

bugfix to set edit mode exclusively from the parent component

set edit mode from parent component

---

projects/material-addons/src/lib/table/column-header.ts
projects/material-addons/src/lib/table/row-action.ts
projects/material-addons/src/lib/table/table-action.ts
projects/material-addons/src/lib/table/table.component.html
projects/material-addons/src/lib/table/table.component.scss
projects/material-addons/src/lib/table/table.component.ts
projects/material-addons/src/lib/table/table.module.ts
projects/material-addons/src/lib/table/table.ts
projects/material-addons/src/public-api.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component-demos/action-table-demo/action-table-demo.component.html
src/app/component-demos/action-table-demo/action-table-demo.component.ts
src/app/example-components/action-table/action-table.component.html
src/app/example-components/action-table/action-table.component.scss
src/app/example-components/action-table/action-table.component.ts
src/assets/i18n/en.json
src/navigation-entries.ts

action table & demo page

---

projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts

fixed missing span error

---

projects/material-addons/src/lib/table/table.component.ts

fixed default table page size

---

projects/material-addons/src/lib/numeric-field/number-format.service.ts

Bugfix German number format detection
1,234.5 -> 1.234,5

fix number format detection

---

projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
projects/material-addons/src/public-api.ts
src/app/app.module.ts
src/app/component-demos/numeric-field-demo/numeric-field-demo.component.html

bugfix reset unit symbol

---

projects/material-addons/src/lib/table/column-header.ts
projects/material-addons/src/lib/table/row-action.ts
projects/material-addons/src/lib/table/table-action.ts
projects/material-addons/src/lib/table/table.component.html
projects/material-addons/src/lib/table/table.component.ts
projects/material-addons/src/lib/table/table.ts
src/app/component-demos/action-table-demo/action-table-demo.component.html
src/app/example-components/action-table/action-table.component.ts

refactoring action table & improvements

---

projects/material-addons/src/lib/quick-list/quick-list.component.ts

bugfix do not emit empty item on init

---

projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.html
projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
projects/material-addons/src/lib/readonly/readonly-form-field.module.ts
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.html
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
src/app/example-components/read-only-field/read-only-field.component.html

add error message to readonly field

---

projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.html
projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.css
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.html
projects/material-addons/src/lib/readonly/readonly-form-field/readonly-form-field.component.ts
src/app/example-components/read-only-field-wrapper/read-only-field-wrapper.component.html
src/app/example-components/read-only-field-wrapper/read-only-field-wrapper.component.ts
src/app/example-components/read-only-field/read-only-field.component.html
src/app/example-components/read-only-field/read-only-field.component.ts

depending on the attributes set, the readonly-form-field either renders an input or a textarea

issue-50: implemented textarea support for the readonly form field (#50)

---

projects/material-addons/src/lib/toolbar/toolbar-action.interface.ts
projects/material-addons/src/lib/toolbar/toolbar.component.css
projects/material-addons/src/lib/toolbar/toolbar.component.html
projects/material-addons/src/lib/toolbar/toolbar.module.ts
src/app/component-demos/toolbar-demo/toolbar-demo.component.ts
src/app/example-components/toolbar/toolbar.component.ts

optionally the ToolbarAction was extended by the MatBadges, a value and a color can be given, the color is either primary, accent or warn, default it is primary
toolbarComponent

add mat-badges to toolbarAction

---

projects/material-addons/src/lib/material-addons.module.ts
projects/material-addons/src/lib/throttle-click/throttle-click.directive.ts
projects/material-addons/src/lib/throttle-click/throttle-click.module.ts
projects/material-addons/src/public-api.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component-demos/throttle-click-demo/throttle-click-demo.component.html
src/app/component-demos/throttle-click-demo/throttle-click-demo.component.ts
src/app/example-components/throttle-click/throttle-click.component.html
src/app/example-components/throttle-click/throttle-click.component.ts
src/assets/i18n/en.json
src/navigation-entries.ts

Implemented directive to throttle button clicks
Throttle directive in lib
Added new example and demo component for the throttle click directive
Added new navigation element "Directives"

directive to throttle a button action (#57)

---

projects/material-addons/src/lib/card/card.component.html
projects/material-addons/src/lib/card/card.module.ts

Added the throttle click directive to the cards save button
card component -> save button

add throttle click directive to save button (#60)

---

projects/material-addons/src/lib/toolbar/toolbar.component.html

add badge function of toolbar actions also to mat-menu in toolbar (which is shown using for e.g. a mobile device)
ToolbarComponent

Show badge in mat menu of toolbar

---

projects/material-addons/src/lib/button/danger-button/danger-button.component.html
projects/material-addons/src/lib/button/danger-button/danger-button.component.ts
projects/material-addons/src/lib/button/flat-button/link-button.component.html
projects/material-addons/src/lib/button/flat-button/link-button.component.ts
projects/material-addons/src/lib/button/icon-button/icon-button.component.html
projects/material-addons/src/lib/button/icon-button/icon-button.component.ts
projects/material-addons/src/lib/button/mad-basic-button.ts
projects/material-addons/src/lib/button/outline-button/outline-button.component.html
projects/material-addons/src/lib/button/outline-button/outline-button.component.ts
projects/material-addons/src/lib/button/primary-button/primary-button.component.html
projects/material-addons/src/lib/button/primary-button/primary-button.component.ts
projects/material-addons/src/lib/quick-list/quick-list.component.html

Fixed disable for mad buttons.
mad buttons

fix disable mad buttons(#67)

---

projects/material-addons/src/lib/table/table.component.html
projects/material-addons/src/lib/table/table.component.scss

fix overflow of table columns (#78)

---

projects/material-addons/src/lib/card/card.component.html
projects/material-addons/src/lib/card/card.component.ts
src/app/example-components/card-editable/card-editable.component.html
src/app/example-components/card-editable/card-editable.component.ts
src/app/example-components/card-readonly/card-readonly.component.html
src/app/example-components/card-readonly/card-readonly.component.ts

add an additional action to mad-card to have the option for more interaction.
card component

add an additionalAction to Card

---

projects/material-addons/src/lib/material-addons.module.ts
projects/material-addons/src/lib/stepper/mad-stepper-animation.ts
projects/material-addons/src/lib/stepper/step-header/step-header.component.html
projects/material-addons/src/lib/stepper/step-header/step-header.component.scss
projects/material-addons/src/lib/stepper/step-header/step-header.component.ts
projects/material-addons/src/lib/stepper/step.component.html
projects/material-addons/src/lib/stepper/stepper.component.html
projects/material-addons/src/lib/stepper/stepper.component.scss
projects/material-addons/src/lib/stepper/stepper.component.ts
projects/material-addons/src/lib/stepper/stepper.module.ts
projects/material-addons/src/public-api.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component-demos/stepper-demo/stepper-demo.component.html
src/app/component-demos/stepper-demo/stepper-demo.component.spec.ts
src/app/component-demos/stepper-demo/stepper-demo.component.ts
src/app/example-components/stepper/stepper.component.html
src/app/example-components/stepper/stepper.component.ts
src/assets/i18n/en.json
src/navigation-entries.ts

Implementation of stepper component

implemented stepper component (#88)

---

projects/material-addons/src/lib/stepper/step-header/step-header.component.html
projects/material-addons/src/lib/stepper/step-header/step-header.component.scss
projects/material-addons/src/themes/common/styles.scss
projects/material-addons/src/themes/pbv.scss

Added validations scss in order to have a unified style for material elements regarding validations

added validation scss class

---

projects/material-addons/src/lib/flowbar/flowbar.component.scss

minor css enhancement
flowbar component

fixed overlay css for flowbar component

---

projects/material-addons/src/lib/flowbar/flowbar.component.html
projects/material-addons/src/lib/flowbar/flowbar.component.ts

Fix selection for flowbar component

fix selection for  flowbar component

---

projects/material-addons/src/lib/toolbar/toolbar.component.html

The coloring of the drop down menu in toolbar component was different to the other icons in the toolbar. These icons are now primary too.
ToolbarComponent

fix coloring of menu in toolbar

---

projects/material-addons/src/lib/toolbar/toolbar.component.html
projects/material-addons/src/lib/toolbar/toolbar.component.ts
projects/material-addons/src/lib/toolbar/toolbar.service.ts
src/app/app.module.ts
src/app/example-components/toolbar/toolbar.component.html
src/app/example-components/toolbar/toolbar.component.ts

Implementation for issue **#102**. <-- Screenshots are found in the issue!
**mad-toolbar**
Added property to always enable "mobile" mode, where toolbar actions are condensed to a burger menu.
No breaking change.
- No breaking change.
- No visible changes after uprading to this version.

Burger Menu for toolbar actions on desktop

---

package-lock.json
src/app/app.module.ts
src/app/component-demos/data-table-demo/data-table-demo.component.html
src/app/component-demos/data-table-demo/data-table-demo.component.ts
src/app/dev-components/data-table/data-table-action-type.ts
src/app/dev-components/data-table/data-table-action.ts
src/app/dev-components/data-table/data-table-column-definition.ts
src/app/dev-components/data-table/data-table-column.ts
src/app/dev-components/data-table/data-table-columns-modal/data-table-columns-modal.component.html
src/app/dev-components/data-table/data-table-columns-modal/data-table-columns-modal.component.scss
src/app/dev-components/data-table/data-table-columns-modal/data-table-columns-modal.component.ts
src/app/dev-components/data-table/data-table-dev.component.html
src/app/dev-components/data-table/data-table-dev.component.scss
src/app/dev-components/data-table/data-table-dev.component.ts
src/app/dev-components/data-table/data-table-dev.module.ts
src/app/dev-components/data-table/data-table-row.ts
src/app/dev-components/data-table/data-table.ts

- async paging
- action column max width
- anchor links in documentation

#75 minor bugfixes

---

src/app/components/navigation/main-navigation.component.scss

Toolbar was Scrollable on iOS, now it is fixed on iOS as well
CSS File of MainNavigation

Fix Toolbar Error For iOS

---

projects/material-addons/src/lib/quick-list/quick-list.component.html
projects/material-addons/src/lib/stepper/step.component.html
projects/material-addons/src/lib/stepper/stepper.module.ts

change "add" button in Quicklist to "Outline" Styling and "next" and "done" button in MatStepper to "Primary" Styling
QuickList
Step

Fix Button Styling for Stepper and Quicklist

---

angular.json
package-lock.json
projects/material-addons/src/lib/data-table/data-table.component.html
projects/material-addons/src/lib/data-table/data-table.component.scss
projects/material-addons/src/lib/data-table/data-table.component.ts

DataTable
- remove click event of checkbox
- fix data-table not working wenn tableData was explicitly set to NULL
DataTable

#75 dataTable-hotfix batch selection not working as intended

---

projects/material-addons/src/lib/card/card.component.html
projects/material-addons/src/lib/card/card.component.scss

change styling of mat-card header with icons
mat-card

Fix styling for mat-card

---

package-lock.json
projects/material-addons/src/lib/quick-list/base-quick-list.component.ts
projects/material-addons/src/lib/quick-list/quick-list-compact/quick-list-compact.component.ts
projects/material-addons/src/lib/quick-list/quick-list.component.ts
projects/material-addons/src/lib/quick-list/quick-list.module.ts
projects/material-addons/src/lib/quick-list/quick-list.ts
projects/material-addons/src/lib/quick-list/reactive-form-quick-list-compact/reactive-form-quick-list-compact.component.html
projects/material-addons/src/lib/quick-list/reactive-form-quick-list-compact/reactive-form-quick-list-compact.component.ts
projects/material-addons/src/lib/quick-list/reactive-form-quick-list/reactive-form-quick-list.component.html
projects/material-addons/src/lib/quick-list/reactive-form-quick-list/reactive-form-quick-list.component.ts
src/app/app.module.ts
src/app/component-demos/quick-list-demo/quick-list-demo.component.html
src/app/component-demos/quick-list-demo/quick-list-demo.component.ts
src/app/example-components/quick-list-reactive-form-basic/quick-list-reactive-form-basic.component.html
src/app/example-components/quick-list-reactive-form-basic/quick-list-reactive-form-basic.component.scss
src/app/example-components/quick-list-reactive-form-basic/quick-list-reactive-form-basic.component.ts
src/app/example-components/quick-list-reactive-form-compact/quick-list-reactive-form-compact.component.html
src/app/example-components/quick-list-reactive-form-compact/quick-list-reactive-form-compact.component.scss
src/app/example-components/quick-list-reactive-form-compact/quick-list-reactive-form-compact.component.ts

Reactive Form Validation for quick lists have been added. 
The difference is, you have to provide a FormArray as Input, instead of an array.
There is also a compact Quick List available.
ReactiveFormQuickListComponent
ReactiveFormQuickListCompactComponent

Reactive form validation for quick list

---

projects/material-addons/src/lib/data-table/data-table.component.ts

fix error when data table pagination is disabled, there is a reading of undefined exception when pagination is disabled
DataTable

fix error when data table pagination is disabled

---

renovate.json

chore: enable Renovate

---

package-lock.json
projects/material-addons/src/lib/numeric-field/numeric-field.directive.ts

autofill decimals is not working on initialization, this is a fix for it.
NumericField Directive

Fix on init numeric field display

---

package-lock.json
projects/material-addons/src/lib/layout/toolbar/toolbar-action.interface.ts
projects/material-addons/src/lib/layout/toolbar/toolbar.component.html
src/app/example-components/toolbar/toolbar.component.ts

add a tooltip to main action button in the toolbar
toolbar component

add tooltip to main action

---

projects/material-addons/src/lib/data-table/configuration/data-table-global-configuration.ts
projects/material-addons/src/lib/data-table/util/data-table-sort-util.ts

Make data table sorting less strict
- data-table-sorting-util
- data-table-global-configuration

bugix data table sorting

---

projects/material-addons/src/lib/data-table/configuration/data-table-global-configuration.ts

Fix sorting configuration of the data table
- data-table-global-configuration

fix data table sorting

---

package-lock.json
projects/material-addons/src/lib/data-table/configuration/data-table-persistence-configuration.ts
projects/material-addons/src/lib/data-table/data-table-filter/data-table-filter-header.directive.ts
projects/material-addons/src/lib/data-table/data-table.component.spec.ts
projects/material-addons/src/lib/data-table/data-table.component.ts
projects/material-addons/src/lib/data-table/data-table.ts
src/app/component-demos/data-table-demo/data-table-demo.component.html
src/app/example-components/data-table-stateful/data-table-stateful.component.html
src/app/example-components/data-table-stateful/data-table-stateful.component.ts

Improve the statefulness of the data-table by providing a config per property
- sort
- filter
- pageSize
---
Fix a small bug with the filter header.
- data-table-persistence-configuration.ts
- data-table.component.ts
- data-table.ts
---
- data-table-filter-header.directive.ts

feat: improve / extend datatable stateful config

---

README.md
package-lock.json
projects/material-addons/package.json
projects/material-addons/src/version.ts

bugfix for new page layout
none

bugfix for new page layout

---

README.md
projects/material-addons/package.json
projects/material-addons/src/version.ts

bugfix for version

---

projects/material-addons/src/lib/data-table/util/data-table-sort-util.spec.ts
projects/material-addons/src/lib/data-table/util/data-table-sort-util.ts

Fixed / improved sorting & enabled tests.
- data-table-sort-util.ts
- data-table-sort-util.spec.ts

fix sorting & enable tests

---

projects/material-addons/src/lib/card/card.component.html
projects/material-addons/src/lib/card/card.component.ts
src/app/component-demos/card-demo/card-demo.component.html
src/app/component-demos/card-demo/card-demo.component.ts
src/app/example-components/card-without-title/card-without-title.component.html
src/app/example-components/card-without-title/card-without-title.component.ts

add option to have a card without title
Card Component

add card-without-title

---

projects/material-addons/src/lib/data-table/data-table.component.ts

Trigger ChangeDetection when TemplateRefs are updated. (In case you are using a wrapper inside the implementing project there might occur errors otherwise.)
- data-table.component.ts

improve template refs

---

projects/material-addons/src/lib/data-table/data-table.component.html
projects/material-addons/src/lib/data-table/data-table.component.spec.ts
projects/material-addons/src/lib/data-table/data-table.component.ts

"Select all" functionality was broken due to "filteredData" not being sorted. We now return filtered & sorted data of the current page.
- data-table.component.ts
- data-table.component.html

fix data table display data

---

projects/material-addons/src/lib/layout/content-panel/content-panel-container-footer/content-panel-container-footer.component.scss
projects/material-addons/src/lib/layout/content-panel/content-panel-container/content-panel-container.component.scss

Fix flowbar layout scroll and footer styles
From this 
into this
- content-panel-container
- content-panel-container-footer

Flowbar layout scroll and footer fix

---

.github/workflows/release.yml
.github/workflows/verify.yml

Have seen the pipelines do not run anymore and you see the deprecation warnings -> upgrde
None

fix: Update workflows to node v20

---

projects/material-addons/src/lib/alert/alert-configuration.ts
projects/material-addons/src/lib/alert/alert.component.ts
projects/material-addons/src/lib/alert/alert.ts
projects/material-addons/src/public_api.ts
projects/material-addons/src/themes/carcat.scss

added settings for carcat.scss regarding alert.component

fixed alignment of icon in alert.component

---

projects/material-addons/src/lib/data-table/data-table.component.html
projects/material-addons/src/lib/stepper/stepper.component.html

- added condition for onExpand call in data table row logic

---

package-lock.json
projects/material-addons/src/lib/readonly/readonly-form-field-wrapper/readonly-form-field-wrapper.component.ts
projects/material-addons/src/lib/stepper/step-header/step-header.component.scss
projects/material-addons/src/lib/stepper/stepper.component.html
projects/material-addons/src/lib/stepper/stepper.component.scss
projects/material-addons/src/themes/common/styles.scss
src/app/example-components/stepper/stepper.component.html

fix: stepper error state color, css, add mat-error to stepper demo

---

projects/material-addons/src/lib/data-table/data-table.component.html
projects/material-addons/src/lib/data-table/data-table.component.scss

- Fixed the positioning of the filter button
DataTable -> columnBased Filter

fix position of filter button in data table

---

projects/material-addons/src/lib/data-table/data-table.component.ts
src/app/example-components/data-table-stateful/data-table-stateful.component.html
src/app/example-components/data-table-stateful/data-table-stateful.component.ts

* Fixed the initial state of the delete filter button in case the `filterValue` has an initial value
* DataTable -> columnBased Filter

fix delete filter button for initial filterValue
